---
image: "quay.io/ansible/molecule:2.22"

services:
  - docker:dind

before_script:
  - apk add linux-headers musl-dev gcc libffi-dev libressl-dev make
  - docker -v
  - python -V
  - pip install pipenv
  - pipenv install
  - ansible --version
  - molecule --version

variables:
  DOCKER_HOST: "tcp://docker:2375"

run:
  script: pipenv run invoke test
  parallel: 4
