---
image: quay.io/ansible/molecule:2.22rc3
services:
  - docker:dind

stages:
  - tests

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"


before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

pulibrary-roles:
  stage: tests
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  script:
    - molecule lint
