---
- hosts: zookeepergcp
  remote_user: pulsys
  become: true
  vars_files:
    - ../site_vars.yml
    - ../group_vars/solrcloud/vault.yml
    - ../group_vars/solrcloud/solrcloud_gcp.yml
  roles:
    - role: roles/pulibrary.openjdk
    - role: roles/pulibrary.deploy-user
    - role: roles/pulibrary.zookeeper
